/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewGUI;

/**
 *
 * @author jeffr
 */
public class VistaRequerimientos extends javax.swing.JFrame {

    /**
     * Creates new form VistaRequerimientos
     */
    public VistaRequerimientos() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Requerimientos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReq_1 = new javax.swing.JButton();
        btnReq_2 = new javax.swing.JButton();
        btnReq_3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 5));

        btnReq_1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReq_1.setText("Requerimiento 1");
        btnReq_1.setBorder(null);
        btnReq_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReq_1.setDefaultCapable(false);
        btnReq_1.setFocusPainted(false);
        btnReq_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReq_1ActionPerformed(evt);
            }
        });

        btnReq_2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReq_2.setText("requerimiento 2");
        btnReq_2.setBorder(null);
        btnReq_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReq_2.setDefaultCapable(false);
        btnReq_2.setFocusPainted(false);
        btnReq_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReq_2ActionPerformed(evt);
            }
        });

        btnReq_3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReq_3.setText("requerimiento 3");
        btnReq_3.setBorder(null);
        btnReq_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReq_3.setDefaultCapable(false);
        btnReq_3.setFocusPainted(false);
        btnReq_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReq_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReq_1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnReq_2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnReq_3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReq_1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReq_2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReq_3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReq_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReq_1ActionPerformed
        VistaRequerimientoTB_1 vr1 = new VistaRequerimientoTB_1();
        vr1.setVisible(true);
    }//GEN-LAST:event_btnReq_1ActionPerformed

    private void btnReq_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReq_2ActionPerformed
        VistaRequerimientoTB_2 vr2 = new VistaRequerimientoTB_2();
        vr2.setVisible(true);
    }//GEN-LAST:event_btnReq_2ActionPerformed

    private void btnReq_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReq_3ActionPerformed
        VistaRequerimientoTB_3 vr3 = new VistaRequerimientoTB_3();
        vr3.setVisible(true);
    }//GEN-LAST:event_btnReq_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRequerimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReq_1;
    private javax.swing.JButton btnReq_2;
    private javax.swing.JButton btnReq_3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
